animal = " perro  feliz "
print(animal.upper())
print(animal.lower())
print(animal.capitalize())
print(animal.title())
print(animal.strip().capitalize())
print(animal.strip().find("fe"))
print(animal.replace("fel", "jel"))
print("fe" in animal)
print("fe" not in animal)
